# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 08:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='hashtag',
            new_name='tags',
        ),
    ]
