# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20160705_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('article', models.ManyToManyField(to='articles.Article')),
            ],
        ),
    ]
