# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-20 04:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_hashtag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='article',
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created']},
        ),
        migrations.DeleteModel(
            name='HashTag',
        ),
    ]
